# Generated by Django 3.2.8 on 2022-11-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
