# Generated by Django 3.2.8 on 2022-11-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_auto_20221118_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.FileField(upload_to='media'),
        ),
    ]
